### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by jeef3** [jeef3/teamcity#7]

**Comment by fjakop** [comment]
Just using the example from the README fails, I've set up a tester as follows:
```
describe('TeamCity', function () {
        it('Tester', function (done) {
            this.timeout(10000);

            var options = {
                username: "user",
                password: "pass",
                baseUrl: "http",
                protocol: "teamcity.my.domain"
            };

            var TeamCity = require('teamcity').TeamCity;
            var teamcity = new TeamCity(options);

            teamcity.builds.get(1234, function (err, builds) {
                if (err) {
                    throw err;
                }
                console.log(builds);
            });
        });
    });
```

Execution results in
```
TypeError: this.client._get is not a function
    at Builds.Locatable.get (/var/packages/arxestolina/node_modules/teamcity/lib/locatable.js:22:21)
    at Context.<anonymous> (/var/project/packages/arxestolina/jobs/build-status/test/test-build-status.js:199:29)
    at Test.Runnable.run (/var/project/packages/arxestolina/node_modules/mocha/lib/runnable.js:216:15)
    at Runner.runTest (/var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:373:10)
    at /var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:451:12
    at next (/var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:298:14)
    at /var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:308:7
    at next (/var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:246:23)
    at Immediate._onImmediate (/var/project/packages/arxestolina/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by fjakop** [comment]
When I use `teamcity._get` directly instead
```
teamcity._get('/app/rest/builds/id:1234', function (err, builds) {
  if (err) {
    throw err;
  }
  console.log(builds);
});
```
it works as expected.

**Comment by jeef3** [comment]
@fjakop cheers for the help and patience! I haven't had a lot of time to work on this, so I'm flying a little blind. Hopefully the changes in https://github.com/jeef3/teamcity/commit/7658f7dbbe1cc27465abfa1b731130ef649d802e can fix that.

**Comment by fjakop** [comment]
Thanks a lot, now it gets over this step and retrieves the build. In case of an error the callback is executed twice, I've tried a fix in PR https://github.com/jeef3/teamcity/pull/8.
Next was to use a locator
```
var buildTypesOfProject = teamcity
                .buildTypeLocator()
                .affectedProject({id: "MyProjectId"});

            // Get some build types
            teamcity.buildTypes.by(buildTypesOfProject, function (err, build) {
                console.log(err);
                console.log(build);
            });
```
which is resulting in
```
TypeError: this.parent.getPath is not a function
    at BuildTypes.getPath (/var/project/packages/arxestolina/node_modules/teamcity/lib/locatable.js:52:32)
    at BuildTypes.Locatable.by (/var/project/packages/arxestolina/node_modules/teamcity/lib/locatable.js:43:31)
    at Context.<anonymous> (/var/project/packages/arxestolina/jobs/build-status/test/test-build-status.js:203:33)
    ...
```
and as far as I understand the js code, the `getPath`-function of `Locatable` is not yet known, eve if the parent is a `Locatable`.
I really would like to support you more, but as I said before, I'm not used to coffe script so my efforts are slow.

**Comment by jeef3** [comment]
> I really would like to support you more, but as I said before, I'm not used to coffe script so my efforts are slow.

Cheers, your patience is appreciated! :smile: Yeah, I wrote this a couple of years ago when I was on a CoffeeScript buzz. Would love to re-write, but will focus on getting this working first.

**Comment by jeef3** [comment]
@fjakop a couple of minor fixes in there. Still trying to get back up-to-speed on the TeamCity API and why I've done things the way I've done them :flushed:

**Comment by fjakop** [comment]
We're getting close. No errors this time, but the generated pathes see to be incorrect when using locators.

```
teamcity
   .buildLocator()
   .buildType({id: "myBuildType"})
   .state('finished')
   .count(2);
```
produces this path `/app/rest/builds/buildType:(id:myBuildType),state:finished,count:2` which leads to a wrong result, i.e. it retrieves the details of one build only.
Instead the intended path for this locator should be imho `/app/rest/builds?locator=buildType:(id:myBuildType),state:finished,count:2`, which retrieves the list of last 2 finished builds.

**Comment by jeef3** [comment]
> produces this path /app/rest/builds/buildType:(id:myBuildType),state:finished,count:2 which leads to a wrong result, i.e. it retrieves the details of one build only.
> Instead the intended path for this locator should be imho /app/rest/builds?locator=buildType:(id:myBuildType),state:finished,count:2, which retrieves the list of last 2 finished builds.

Hmm, I was following the [TeamCity API](https://confluence.jetbrains.com/display/TCD9/REST+API#RESTAPI-Locator) docs for this URL. The docs read like that URL should work, but maybe that's only sometimes (the docs are a little vague in parts). I'll switch them over to use the `?locator=` syntax. :+1:

**Comment by jeef3** [comment]
@fjakop I just had a quick look at this and apparently the locator syntax I've used does work in some cases, and actually in other cases it is required, such as if you are accessing a child resource, such as:

```
Create a new empty build configuration: POST plain text (name) to
http://teamcity:8111/httpAuth/app/rest/projects/<projectLocator>/buildTypes
```

And

```
List builds: GET http://teamcity:8111/httpAuth/app/rest/builds/?locator=<buildLocator>
Get details of a specific build: GET http://teamcity:8111/httpAuth/app/rest/builds/<buildLocator>  (also supports DELETE to delete a build)
```

Although in this second example, I'm not sure what the difference is? Both URLs look like they should do the same thing? They both provide a `buildLocator`, why does one list builds and the other get details of?

**Comment by fjakop** [comment]
Ok, let me clarify the dense jungle of TC Rest API documentation, which is, well, confusing.

If we use the syntax `/app/rest/builds/<buildLocator>`, it will always return details. (applies to projects, buildTypes etc. also).
The locator passed after the slash will always ignore the `count` dimension, as it returns the last build's details.

The syntax `/app/rest/builds/?locator=<buildLocator>` will _never_ return details of a build, but always a list of builds (wrapped in a result JSON-object) which may be also size 0.

So there's a difference whether one would retrieve a list of objects or the details of an object and this is reflected by the different locator syntaxes.

**Comment by jeef3** [comment]
Hmm, okay. That... almost makes sense :smile:

So for the API, do we maybe need something like:

```
teamcity.builds.by(locator, cb)
// /app/rest/builds?locator=<buildLocator>

teamcity.builds.get(1, cb)
// /app/rest/builds/1

teamcity.builds.get(locator, cb);
// /app/rest/builds/<buildLocator>
```

So that `by(locator, cb)` always uses the `?locator=` syntax and `get(id|locator, cb)` always uses the `/locator` syntax?

**Comment by fjakop** [comment]
Yes, `/app/rest/builds/1` is shorthand for `/app/rest/builds/id:1` which is a locator.

**Comment by jeef3** [comment]
Cool, thanks for the clarification :+1:

**Comment by jeef3** [comment]
@fjakop There, have altered the behaviour of `get` and `by`. I haven't renamed them yet though. I just want to make sure the names still make sense when chained:

```
teamcity.projects.get('project1')
  .buildTypes.get('bt1')
  .builds.by({ user: { id: 1 } }, cb);

// vs

teamcity.projects.details('project1')
  .buildTypes.details('bt1')
  .builds.list({ user: { id: 1 } }, cb);
```

At the moment the chaining works by always returning itself. It makes an API call for each callback. This has the unintended side-effect of allowing you to do odd things like:

```
teamcity.projects.get('project1', function (projects) { /* returns project */ })
  .buildTypes.get('bt1', function (buildTypes) { /* returns build types for project */ })
  .builds.by({ user: { id: 1 } }, function (builds) { /* returns builds for combined locators above */ });

// Makes three API calls
// - /app/rest/projects/id:project1
// - /app/rest/projects/id:project1/buildTypes/id:bt1
// - /app/rest/projects/id:project1/buildTypes/id:bt1/builds?locator=user:(id:1)
```

I guess the other option is to consider singular functions for the chaining, since using the locator like that always returns the first result anyway? (is that how it works?)

```
// /app/rest/projects/id:project1/buildTypes/id:bt1/builds?locator=user:(id:1)
teamcity.project('project1')
  .buildType('bt1')
  .builds.list({ user: { id: 1 } }, cb);
```

If I do that, then I could also return a promise (or drop the callbacks completely in favour of promises)

```
teamcity.project('project1')
  .buildType('bt1')
  .builds.list({ user: { id: 1 } })
  .then(function (builds) {
    // builds...
  });
```

Appreciate the feedback :smile:

**Comment by fjakop** [comment]
Well, I do not really understand what's happening with the results of the first and second API call, but the third one is perfectly legal seen from TC's point of view.

It would return all builds triggered by user with id 1 which belong to build type with id bt1 if and only if bt1 belongs to project1.

You see, there's some redundancy as the call to `/app/rest/buildTypes/id:bt1/builds?locator=user:(id:1)` would exactly retrieve the same set of builds, because the build type is identified by id (in this case). But I would not care about this redundancy in first place.

Since this example uses the `?locator=` syntax in the third call it will not return details. The first and second one will provide details of project or build type.

For the start it may be feasible to make the chaining singular, but it is to be considered, that TC allows locator chaining like that `/app/rest/projects/id:project1/buildTypes/?locator=paused:true&fields=buildType(id,project,builds($locator(status:failure),build(id,number,status)))`
This means basically: 
* get projet1's build types
* which are paused
* and return only the fields id, project and builds
* but only builds which failed
* and return only the builds' fields id,number and status

**Comment by jeef3** [comment]
Yeah, I see what you're saying about the redundant projects call. I was just trying to show an example of chaining and the nested nature of TeamCity's API.

``` javascript
teamcity
  .buildTypes.get('bt1')
  .builds.by({ user: { id: 1 } }, cb);

// vs

teamcity
  .buildTypes.details('bt1')
  .builds.list({ user: { id: 1 } }, cb);

// vs

teamcity
  .buildType('bt1') /* or */ .buildType({ id: 'bt1' })
  .builds.list({ user: { id: 1 } }), cb); /* returns promise */
```

You seem to have a better understanding of the TeamCity API than I do, so I'm keen to hear your thoughts. This API is still only preview, I would like to have it make sense, so let me know your preferences :smile:

> For the start it may be feasible to make the chaining singular, but it is to be considered, that TC allows locator chaining like that `/app/rest/projects/id:project1/buildTypes/?locator=paused:true&fields=buildType(id,project,builds($locator(status:failure),build(id,number,status)))`

Wow, that's intense. I didn't know about locator nesting like that or the "return only the fields" part. Did you have any thoughts on how you would call that? It's getting messy, but would this work?

``` javascript
buildLocator = new BuildLocator()
  .status('failure')
  .fields(['id', 'number', 'status']);

buildTypeLocator = new BuildTypeLocator()
  .paused(true)
  .fields([
    // Maybe optionally use some constants here
    BuildTypeFields.ID,
    BuildTypeFields.PROJECT,

    { 'builds': buildLocator }, 
    // or, and this is a bit of ES6
    { [BuildTypeFields.BUILDS]: buildLocator },
    // or, it might be possible to infer the name and just use:
    buildLocator
  ]);

teamcity
  .project({ id: 'project1'})
  .buildTypes.list(buildTypeLocator);
```

**Comment by fjakop** [comment]
If I look on the first examples above, your way looks cleaner when chaining (get/by). Imo `buildTypes.get('bt1')` and `buildTypes('bt1')` should be the same, but if you decide to support only one version I would vote for `buildTypes.get('bt1')` for I consider using an explicit method more readable.

The locator nesting is described in https://youtrack.jetbrains.com/issue/TW-26176#comment=27-681180. I was looking for API calls which fit my needs and stumbled upon this, which greatly reduces API calls in my case.

As for the approach with fields and nested locators, why do you think this is messy? Looks like a straightforward approach. 
BTW, I'm mostly Java programmer, not JS, so putting things in variables looks less odd to me than using the n-th nested layer :)

Introducing field names is a good idea, because the list of supported fields is not well documented.

**Comment by jeef3** [comment]
Sweet, I'm going to try and work in those fields and nested locator pieces. In the mean time, how is the latest commit (bff1ed5) working for you? Last you mentioned I think there was some errors with the locators. Are they working closer to expected now?

**Comment by fjakop** [comment]
Yes, the locators work now since fix in https://github.com/jeef3/teamcity/commit/bff1ed5931abfde56e95c110c4d48f81ba76155e.

Some other oddity I've noticed: When I put
```
"dependencies": {
    "teamcity": "jeef3/teamcity"
 },
```
in my `package.json` and run `npm install` it does not generate the `lib` folder, instead I'm left with the files located directly in the top-level directory. I have to clone the repo, run `gulp build` and copy the `lib` folder into node_modules/teamcity.

**Comment by jeef3** [comment]
> in my package.json and run npm install it does not generate the lib folder, instead I'm left with the files located directly in the top-level directory. I have to clone the repo, run gulp build and copy the lib folder into node_modules/teamcity.

Turns out I had forgotten how to `npm publish`! :flushed: 

You should be able to install now with `npm install teamcity@preview` (I'll keep updating the `preview` tag) or `npm install teamcity@1.0.0-preview.1` (where I'll update `.1` each time) for the preview I *just* published.

**Comment by fjakop** [comment]
Hm, either variant leaves me with a `node_modules/teamcity` folder containing now `src` and `test`, but no `lib` folder. I suppose that `gulp build` is to be automatically executed when I do `npm install teamcity@preview`?
Or is it intended that I have to run `npm install` subsequently inside `node_modules/teamcity` folder?

**Comment by jeef3** [comment]
@fjakop totally my bad. I removed the `.npmignore` when I shouldn't have. Fixed now with `npm install teamcity@preview`.

**Comment by jeef3** [comment]
As per #9 I'm heading in some slightly different directions for some parts of the API. In part, in an effort to introduce promises, but also to _try_ and disambiguate the difference between getting one item and getting a list.

``` JavaScript
// Use build locators
const projectLocator = new ProjectLocator()
  .name('Project One');

// Or plain objects
const buildTypeLocator = {
  paused: true,
  fields: ['id', 'number', 'status']
};

teamcity
  // .by() sets the locator only and is chaining
  .projects.by(projectLocator)
  // .list() or .get() accepts a locator and a callback, and returns a promise.
  .buildTypes.list(buildTypeLocator);
```

So `get()`, `list()` and `all()` all accept a `locator` and `callback`, as well as terminate the chain by making the API call and returning a `Promise`. `by()` is used for setting locators in a chain, such as when you want to nest.

You could do this:

``` javascript
teamcity
  .projects.by(projectLocator)
  .list(anotherProjectLocator);
```

But the `list()` call would override the `by()` call. Or I could make it error (_locator already set_?).

**Comment by fjakop** [comment]
This chaining looks good, I just do not get it how these approaches combine.
When we use `by(locator)` this will not issue the REST call, right? So I can chain as lon as I like for e.g. fields. When I terminate this chain it can be done by `get()` or `list()`, whereas `get()` returns only item and `list()` multiple objects. Am I on track so far? 
If yes, where's the need to provide any arguments to the terminal calls? (Sorry, I'm Java developer, in my mind I compare this with Java 8's stream feature)

**Comment by jeef3** [comment]
> This chaining looks good, I just do not get it how these approaches combine.
> When we use by(locator) this will not issue the REST call, right? So I can chain as lon as I like for e.g. fields. When I terminate this chain it can be done by get() or list(), whereas get() returns only item and list() multiple objects. Am I on track so far?

Yup, that's correct. But note that you can't call `by()` multiple times, as it just sets the locator each time, not merge. So you would build up your locator first, including fields, then call `by(locator)`. But you can call it again on nested objects, like:

``` javascript
teamcity
  .projects.by(projectLocator)
  .buildTypes.by(buildTypeLocator)
  .builds.by(buildsLocator)
  .list();

// Which would actually be the same as:

teamcity
  .projects.by(projectLocator)
  .buildTypes.by(buildTypeLocator)
  .builds.list(buildsLocator);
```

Of course, I'm open to suggestions on the names of all these `by()`, `get()`, `list()` etc. `by()` could easily be `setLocator()`, I was just trying for a fluent sounding API.

> If yes, where's the need to provide any arguments to the terminal calls? (Sorry, I'm Java developer, in my mind I compare this with Java 8's stream feature)

I'm not sure what you mean here? Do you mean 'why bother passing arguments to `get()`, `list()`?

**Comment by fjakop** [comment]
Right, that was my point. But if the `list(locator)` is the same as `by(locator).list()` it's perfect for me.

**Comment by jeef3** [comment]
@fjakop I've been trying to find documentation on the `$locator` syntax you mentioned. The link you provided only mentions the use of `fields`, not the nested locators via `$locator`.

Also, I've been thinking about the fields, they aren't really part of the locator, so I was thinking of maybe doing them separately. Maybe something like:

``` javascript
teamcity.projects
  .by({ id: 'p1' })
  .fields([ 'name' ]);
```

That puts it on `Projects` object. it does however mean I get it with `get()`, since that makes the call. Unless it was passed in as another param, maybe `get(locator, fields, cb)`.

Anyway, for now I'm focusing on getting the locators finished and core API calls done.
